add patch for post-checkout

diff --git a/post-checkout b/post-checkout
--- a/post-checkout
+++ b/post-checkout
@@ -1,5 +1,9 @@
 #!/bin/sh
 
+## setup lfs
+command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/post-checkout'.\n"; exit 2; }
+git lfs post-checkout "$@"
+
 ## setup user info
 email=""
 name=""
@@ -29,7 +33,7 @@ while read line; do
 done < ~/.ssh/config
 
 lname="$(git config --local user.name)"
-if [[ $lname != $name ]]; then
+if [[ $lname != $name && $name != "" && $name != "git" ]]; then
 	git config user.name $name
 	echo "set repo ${repo}'s user.name to ${name}"
 
